// The allmiibo-sync mascot: an original 8-bit pirate (traced from our own
// SVG, no Nintendo IP) standing on a red NFC dock. Rendered as inline SVG
// <rect> pixels so it stays crisp at any size and needs no image files.
//
// The coat/hat/feather/emblem are separate colour channels; FINISHES lists
// the selectable colourways (Settings). Index 6 — SILVER — is the default.

export const PIRATE_BODY = `
................................
............kkkkkkkk............
.......FF..kHHHHHHHHk...........
.....FFFF..kHHEHHEHHk...........
.....FFFF..kHHHEEHHHk...........
....FFFF...kHHEHHEHHk...........
....FFFFkkk..........kk.........
.....FkkHHHHHHHHHHHHHHHk.ggg....
.......kkkkkkkkkkkkkkkk..g.gg...
..........kkkkkkkkkk.....g.gg...
.........kkkkkkkkkkkk......gg...
.........kssskkkksksk....gg.....
.........kddddddddddk..bbgg.....
.........kddddddddddkbbbbgg.....
.........kdddddsssddkbbbb.......
......kkkkddddddddddkbbk........
.....kbbbbdddrrrrrrbbbbbk.......
.....kbbbb.ddwwwwwwbbbbbk.......
.....kbbbb..drrrrrrbbbbbk.......
.....kbggg...wwwwwwbbbbbk.......
.....ssgkg...rrrrrrbbbbbk.......
.....ssgkg..dddggdddbbbb........
.....kbggg..dddggdddbbbb........
.....wwbbbddddddddddbbbb........
....wwbbbbdddddddddd............
...ww.....dddddddddd............
kwww.....dddd....dddd...........
.........dddd....dddd...........
.........pp........dddd.........
.........pp........dddd.........
........pp..........ddddd.......
........kk..........kkkkk.......`;

export const DOCK32 = `
......KKKKKKKKKKKKKKKKKKKK......
.....KDDDDDDDDDDDDDDDDDDDDK.....
.....KDeeeeeeeeeeeeeeeeeeDK.....
.....KDDDDDDDDDDDDDDDDDDDDK.....
.....KDDDDDDDDDDDDDDDDDDDDK.....
......KKKKKKKKKKKKKKKKKKKK......`;

export const BASE_COLORS = {k:'#111111', b:'#2c59b2', r:'#c7281d', w:'#f3efe6', s:'#f29f63',
               d:'#3b2219', g:'#8d8c8a', p:'#8f5c38', E:'#f3efe6', H:'#2c59b2', F:'#c7281d', K:'#1a1a1a', D:'#9a2a26', e:'#c23a34'};

// [name, coat, coatShade, emblemOverride, hatOverride, featherOverride]
export const FINISHES = [
  ['CRIMSON','#c0392b','#7a2018'], ['NAVY','#2c4a8a','#1a2f5a'],
  ['FOREST','#3a7a3a','#245224'],  ['PLUM','#7a3f9a','#4f2668'],
  ['TEAL','#2a8a7e','#1a5a52'],    ['RUST','#c0621f','#8a4212'],
  ['SILVER','#C9C7C4','#8a8885',null,'#c7281d','#f3efe6'],    ['SLATE','#4a5568','#2f3648'],
  ['GOLD','#c8952a','#8a6212'],    ['MAGENTA','#b0367a','#7a2050'],
  ['EMERALD','#1f8a5a','#125a3a'], ['ASH','#6a6a72','#42424a'],
];

export const DEFAULT_FINISH = 6; // SILVER

// Render a pixel map into crisp <rect> pixels, preserving aspect ratio.
// '.' and unknown chars are transparent.
export function grid(map, colors, px) {
  const rows = map.replace(/^\n+|\n+$/g, '').split('\n').map((r) => r.trim());
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  let rects = '';
  rows.forEach((row, y) => [...row].forEach((c, x) => {
    if (colors[c]) rects += `<rect x="${x}" y="${y}" width="1" height="1" fill="${colors[c]}"/>`;
  }));
  return `<svg viewBox="0 0 ${w} ${h}" width="${Math.round(px * w / h)}" height="${px}" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
}

export function finishColors(i = DEFAULT_FINISH) {
  const [, coat, , emblem, hat, feather] = FINISHES[i] ?? FINISHES[DEFAULT_FINISH];
  return { ...BASE_COLORS, b: coat, H: hat || coat, E: emblem || BASE_COLORS.E, F: feather || BASE_COLORS.F };
}

// The full mascot (pirate on dock) at a given pixel height.
export function pirateMark(px, finish = DEFAULT_FINISH) {
  return grid(PIRATE_BODY + DOCK32, finishColors(finish), px);
}
